### ISSUE TITLE
Impossible to run guard after init

### ISSUE THREAD

**Issue by tuxtux59** [yatmsu/guard-slim-lint#1]
Hi,

I'm trying to use your gem but guard do not seems to want.
Here is my error:
`[..]/.rvm/gems/ruby-2.5.1/gems/guard-2.15.0/lib/guard/internals/plugins.rb:45:in 'block (2 levels) in matcher_for': undefined method 'name' for nil:NilClass (NoMethodError)
`
After quick search I found that a short code line in your `slim_lint.rb`file. Accordingly to [guard](https://github.com/guard/guard/wiki/Create-a-guard#inline-guard), The initialize definition should end with call of `super`

I guess it could be great to try and release a new version of you gem 👍 

Best regards

### Actual configuration
ruby: 2.5.1
guard: 2.15.0

**Comment by yatmsu** [comment]
@tuxtux59 Thanks for the report. I'll deal with it right away.

**Comment by tuxtux59** [comment]
Thanks :)
